mixed-port: 7897
allow-lan: true
bind-address: "*"
mode: rule
log-level: info

proxies:
  - name: "JP1"
    server: 203.10.98.187
    port: 443
    udp: true
    skip-cert-verify: true
    sni: www.bing.com
    type: hysteria2
    password: 9c42ecbb-ea39-4814-b461-f837709ac77d

proxy-groups:
  - name: "Proxy"
    proxies:
      - JP1
    type: select

rules:
  - MATCH,Proxy
