mixed-port: 7897
allow-lan: true
bind-address: "*"
mode: rule
log-level: info

proxies:
  - name: "JP1"
    server: ${PROXY_SERVER}
    port: 443
    udp: true
    skip-cert-verify: true
    sni: www.bing.com
    type: hysteria2
    password: ${PROXY_PASSWORD}

proxy-groups:
  - name: "Proxy"
    proxies:
      - JP1
    type: select

rules:
  - MATCH,Proxy
